#ifdef __APPLE__
  #define NK_SHADER_VERSION "#version 150\n"
#else
  #define NK_SHADER_VERSION "#version 300 es\n"
#endif

struct shader_codes {
    char* vertex_shader =
        NK_SHADER_VERSION
        "uniform mat4 ProjMtx;\n"
        "in vec2 Position;\n"
        "in vec2 TexCoord;\n"
        "in vec4 Color;\n"
        "in float Index;\n"
        "out vec2 Frag_UV;\n"
        "out vec4 Frag_Color;\n"
        "out float Cmd_Idx;\n"
        "void main() {\n"
        "   Frag_UV = TexCoord;\n"
        "   Frag_Color = Color;\n"
        "   Cmd_Idx = Index;\n"
        "   gl_Position = ProjMtx * vec4(Position.xy, 0, 1);\n"
        "}\n";

    char* fragment_shader =
        NK_SHADER_VERSION
        "precision mediump float;\n"
        "uniform sampler2D Texture;\n"
        "in vec2 Frag_UV;\n"
        "in vec4 Frag_Color;\n"
        "in float Cmd_Idx;\n"
        "out vec4 Out_Color;\n"
        "void main(){\n"
        "   Out_Color = Frag_Color * texture(Texture, Frag_UV.st);\n"
        "   if (Cmd_Idx == 0.f) {\n"
        "       Out_Color.r += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 1.f) {\n"
        "       Out_Color.g += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 2.f) {\n"
        "       Out_Color.b += 0.3f;\n"
        "   };\n"
         "   if (Cmd_Idx == 3.f) {\n"
         "       Out_Color.r += 0.3f;\n"
         "       Out_Color.g += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 4.f) {\n"
         "       Out_Color.g += 0.3f;\n"
         "       Out_Color.b += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 5.f) {\n"
         "       Out_Color.b += 0.3f;\n"
         "       Out_Color.r += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 6.f) {\n"
         "       Out_Color.r += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 7.f) {\n"
         "       Out_Color.g += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 8.f) {\n"
         "       Out_Color.b += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 9.f) {\n"
         "       Out_Color.r += 0.3f;\n"
         "       Out_Color.g += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 10.f) {\n"
         "       Out_Color.g += 0.3f;\n"
         "       Out_Color.b += 0.3f;\n"
         "   };\n"
         "   if (Cmd_Idx == 11.f) {\n"
         "       Out_Color = vec4(0.f, 0.f, 0.f, 1.f);\n"
         "   };\n"
        "   if (Cmd_Idx == 12.f) {\n"
        "       Out_Color.r += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 13.f) {\n"
        "       Out_Color.g += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 14.f) {\n"
        "       Out_Color.b += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 15.f) {\n"
        "       Out_Color.r += 0.3f;\n"
        "       Out_Color.g += 0.3f;\n"
        "   };\n"
        "   if (Cmd_Idx == 16.f) {\n"
        "       Out_Color.g += 0.3f;\n"
        "       Out_Color.b += 0.3f;\n"
        "   };\n"
        "}\n";
};